#!/usr/bin/env bash

harbor_creds() {
  local store
  store="$(python3 -c "import json,os;print(json.load(open(os.path.expanduser('~/.docker/config.json'))).get('credsStore',''))")"
  echo "${REG}" | "docker-credential-${store}" get
}

ensure_project() {
  local cred u p status
  cred="$(harbor_creds)"
  u="$(echo "${cred}" | python3 -c "import sys,json;print(json.load(sys.stdin)['Username'])")"
  p="$(echo "${cred}" | python3 -c "import sys,json;print(json.load(sys.stdin)['Secret'])")"
  echo "==> ensuring Harbor project agentsmesh"
  status="$(curl -sk -u "${u}:${p}" -o /dev/null -w "%{http_code}" \
    -X POST "https://${REG}/api/v2.0/projects" \
    -H "Content-Type: application/json" \
    -d '{"project_name":"agentsmesh","public":true}')"
  [[ "${status}" == "201" || "${status}" == "409" ]] || {
    echo "create Harbor project failed: HTTP ${status}" >&2
    return 1
  }
  echo "  create project -> HTTP ${status}"
}

manifest_digest() {
  local image="$1" digest="" attempt=1
  until digest="$(docker buildx imagetools inspect "${image}" --format '{{.Manifest.Digest}}')" &&
    [[ "${digest}" =~ ^sha256:[a-f0-9]{64}$ ]]; do
    [[ "${attempt}" -ge 4 ]] && {
      echo "invalid registry digest for ${image}: ${digest}" >&2
      return 1
    }
    echo "  registry manifest query failed; retry ${attempt}/4..." >&2
    sleep 3
    attempt=$((attempt + 1))
  done
  printf '%s' "${digest}"
}

docker_build_with_retry() {
  local file="$1" tag="$2" attempt=1
  until docker_build_with_heartbeat "${file}" "${tag}"; do
    [[ "${attempt}" -ge 4 ]] && return 1
    echo "  docker build failed; retry ${attempt}/4 in 5s..." >&2
    sleep 5
    attempt=$((attempt + 1))
  done
}

docker_build_with_heartbeat() {
  local file="$1" tag="$2" build_pid status
  docker build --platform "${PLATFORM}" \
    -f "${REPO_ROOT}/${file}" \
    -t "${tag}" \
    "${REPO_ROOT}" &
  build_pid=$!
  trap 'kill -TERM "${build_pid}" 2>/dev/null || true' INT TERM
  while kill -0 "${build_pid}" 2>/dev/null; do
    sleep 20
    kill -0 "${build_pid}" 2>/dev/null && echo "  docker build still running..."
  done
  wait "${build_pid}" && status=0 || status=$?
  trap - INT TERM
  return "${status}"
}

docker_push() {
  local file="$1" dest="$2"
  local tag="${PROJ}/${dest}:latest"
  echo "==> docker build ${file} -> ${tag} (${PLATFORM})"
  docker_build_with_retry "${file}" "${tag}"
  docker push "${tag}"
  local digest
  digest="$(manifest_digest "${tag}")"
  case "${dest}" in
    backend) PLATFORM_DIGEST_BACKEND="${digest}" ;;
    marketplace) PLATFORM_DIGEST_MARKETPLACE="${digest}" ;;
    marketplace-web) PLATFORM_DIGEST_MARKETPLACE_WEB="${digest}" ;;
    relay) PLATFORM_DIGEST_RELAY="${digest}" ;;
    web) PLATFORM_DIGEST_WEB="${digest}" ;;
    web-admin) PLATFORM_DIGEST_WEB_ADMIN="${digest}" ;;
  esac
}

write_platform_release() {
  local release_dir="${REPO_ROOT}/deploy/kubernetes/cluster-oilan/release"
  local output="${release_dir}/kustomization.yaml"
  local temporary="${output}.tmp"
  mkdir -p "${release_dir}"
  cat > "${temporary}" <<EOF
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Generated by push-images.sh platform. deploy.sh rejects mutable platform images.
images:
  - name: ${PROJ}/backend
    digest: ${PLATFORM_DIGEST_BACKEND}
  - name: ${PROJ}/marketplace
    digest: ${PLATFORM_DIGEST_MARKETPLACE}
  - name: ${PROJ}/marketplace-web
    digest: ${PLATFORM_DIGEST_MARKETPLACE_WEB}
  - name: ${PROJ}/relay
    digest: ${PLATFORM_DIGEST_RELAY}
  - name: ${PROJ}/web
    digest: ${PLATFORM_DIGEST_WEB}
  - name: ${PROJ}/web-admin
    digest: ${PLATFORM_DIGEST_WEB_ADMIN}
EOF
  mv "${temporary}" "${output}"
  echo "==> wrote immutable platform digests to ${output}"
}

registry_digest() {
  local image="$1" digest
  digest="$(manifest_digest "${PROJ}/${image}:latest")"
  printf '%s' "${digest}"
}

mirror() {
  local src="$1" dest="$2"
  echo "==> mirror ${src} -> ${PROJ}/${dest} (multi-arch index)"
  local n=1
  until docker buildx imagetools create --tag "${PROJ}/${dest}" "${src}"; do
    [[ "${n}" -ge 4 ]] && {
      echo "  imagetools failed after 4 tries: ${src}" >&2
      return 1
    }
    echo "  retry ${n}/4 in 8s..." >&2
    sleep 8
    n=$((n + 1))
  done
}
