#!/usr/bin/env bash
# Build + push every image Do Worker needs into the cluster Harbor so pods
# on doops-114-k8s pull from repo.aiedulab.cn:8443/agentsmesh/* (fast, node-local).
#
#   ./push-images.sh all        # platform + infra + runners
#   ./push-images.sh platform   # backend/marketplace/marketplace-web/relay/web/web-admin/mobile
#   ./push-images.sh mobile-access # backend/relay/mobile only
#   ./push-images.sh marketplace-core # backend/marketplace/marketplace-web/web
#   ./push-images.sh web        # rebuild Web and retain other current digests
#   ./push-images.sh marketplace-web # rebuild public marketplace and retain other current digests
#   ./push-images.sh infra      # postgres/redis/minio/mc/kubectl mirrors
#   ./push-images.sh runners    # agent-runtime images (claude/codex/gemini/grok/openclaw/hermes/e2e-echo)
#
# The build host must already be `docker login repo.aiedulab.cn:8443`.
set -euo pipefail

REG="repo.aiedulab.cn:8443"
PROJ="${REG}/agentsmesh"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
TARGET="${1:-all}"
PLATFORM="${PLATFORM:-linux/amd64}"
PLATFORM_DIGEST_BACKEND=""
PLATFORM_DIGEST_MARKETPLACE=""
PLATFORM_DIGEST_MARKETPLACE_WEB=""
PLATFORM_DIGEST_RELAY=""
PLATFORM_DIGEST_WEB=""
PLATFORM_DIGEST_WEB_ADMIN=""

harbor_creds() {
  local store
  store="$(python3 -c "import json,os;print(json.load(open(os.path.expanduser('~/.docker/config.json'))).get('credsStore',''))")"
  echo "${REG}" | "docker-credential-${store}" get
}

ensure_project() {
  local cred u p status
  cred="$(harbor_creds)"
  u="$(echo "${cred}" | python3 -c "import sys,json;print(json.load(sys.stdin)['Username'])")"
  p="$(echo "${cred}" | python3 -c "import sys,json;print(json.load(sys.stdin)['Secret'])")"
  echo "==> ensuring Harbor project agentsmesh"
  status="$(curl -sk -u "${u}:${p}" -o /dev/null -w "%{http_code}" \
    -X POST "https://${REG}/api/v2.0/projects" \
    -H "Content-Type: application/json" \
    -d '{"project_name":"agentsmesh","public":true}')"
  [[ "${status}" == "201" || "${status}" == "409" ]] || {
    echo "create Harbor project failed: HTTP ${status}" >&2
    return 1
  }
  echo "  create project -> HTTP ${status}"
}

manifest_digest() {
  local image="$1" digest="" attempt=1
  until digest="$(docker buildx imagetools inspect "${image}" --format '{{.Manifest.Digest}}')" &&
    [[ "${digest}" =~ ^sha256:[a-f0-9]{64}$ ]]; do
    [[ "${attempt}" -ge 4 ]] && {
      echo "invalid registry digest for ${image}: ${digest}" >&2
      return 1
    }
    echo "  registry manifest query failed; retry ${attempt}/4..." >&2
    sleep 3
    attempt=$((attempt + 1))
  done
  printf '%s' "${digest}"
}

# docker_push <dockerfile> <dest_repo>
docker_push() {
  local file="$1" dest="$2"
  local tag="${PROJ}/${dest}:latest"
  echo "==> docker build ${file} -> ${tag} (${PLATFORM})"
  docker build --platform "${PLATFORM}" \
    -f "${REPO_ROOT}/${file}" \
    -t "${tag}" \
    "${REPO_ROOT}"
  docker push "${tag}"
  local digest
  digest="$(manifest_digest "${tag}")"
  case "${dest}" in
    backend)     PLATFORM_DIGEST_BACKEND="${digest}" ;;
    marketplace) PLATFORM_DIGEST_MARKETPLACE="${digest}" ;;
    marketplace-web) PLATFORM_DIGEST_MARKETPLACE_WEB="${digest}" ;;
    relay)       PLATFORM_DIGEST_RELAY="${digest}" ;;
    web)         PLATFORM_DIGEST_WEB="${digest}" ;;
    web-admin)   PLATFORM_DIGEST_WEB_ADMIN="${digest}" ;;
  esac
}

write_platform_release() {
  local release_dir="${REPO_ROOT}/deploy/kubernetes/cluster-oilan/release"
  local output="${release_dir}/kustomization.yaml"
  local temporary="${output}.tmp"
  mkdir -p "${release_dir}"
  cat > "${temporary}" <<EOF
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Generated by push-images.sh platform. deploy.sh rejects mutable platform images.
images:
  - name: ${PROJ}/backend
    digest: ${PLATFORM_DIGEST_BACKEND}
  - name: ${PROJ}/marketplace
    digest: ${PLATFORM_DIGEST_MARKETPLACE}
  - name: ${PROJ}/marketplace-web
    digest: ${PLATFORM_DIGEST_MARKETPLACE_WEB}
  - name: ${PROJ}/relay
    digest: ${PLATFORM_DIGEST_RELAY}
  - name: ${PROJ}/web
    digest: ${PLATFORM_DIGEST_WEB}
  - name: ${PROJ}/web-admin
    digest: ${PLATFORM_DIGEST_WEB_ADMIN}
EOF
  mv "${temporary}" "${output}"
  echo "==> wrote immutable platform digests to ${output}"
}

registry_digest() {
  local image="$1" digest
  digest="$(manifest_digest "${PROJ}/${image}:latest")"
  printf '%s' "${digest}"
}

mirror() {
  local src="$1" dest="$2"
  echo "==> mirror ${src} -> ${PROJ}/${dest} (multi-arch index)"
  local n=1
  until docker buildx imagetools create --tag "${PROJ}/${dest}" "${src}"; do
    [[ "${n}" -ge 4 ]] && { echo "  imagetools failed after 4 tries: ${src}" >&2; return 1; }
    echo "  retry ${n}/4 in 8s..." >&2; sleep 8; n=$((n+1))
  done
}

push_platform() {
  docker_push backend/Dockerfile backend
  docker_push marketplace/Dockerfile marketplace
  docker_push clients/marketplace-web/Dockerfile marketplace-web
  docker_push relay/Dockerfile relay
  docker_push clients/web/Dockerfile web
  docker_push clients/web-admin/Dockerfile web-admin
  docker_push clients/mobile-lovable/Dockerfile mobile
  write_platform_release
}

push_marketplace_core() {
  docker_push backend/Dockerfile backend
  docker_push marketplace/Dockerfile marketplace
  docker_push clients/marketplace-web/Dockerfile marketplace-web
  docker_push clients/web/Dockerfile web
  PLATFORM_DIGEST_RELAY="$(registry_digest relay)"
  PLATFORM_DIGEST_WEB_ADMIN="$(registry_digest web-admin)"
  write_platform_release
}

push_mobile_access() {
  docker_push backend/Dockerfile backend
  docker_push relay/Dockerfile relay
  docker_push clients/mobile-lovable/Dockerfile mobile
}

push_web() {
  docker_push clients/web/Dockerfile web
  PLATFORM_DIGEST_BACKEND="$(registry_digest backend)"
  PLATFORM_DIGEST_MARKETPLACE="$(registry_digest marketplace)"
  PLATFORM_DIGEST_MARKETPLACE_WEB="$(registry_digest marketplace-web)"
  PLATFORM_DIGEST_RELAY="$(registry_digest relay)"
  PLATFORM_DIGEST_WEB_ADMIN="$(registry_digest web-admin)"
  write_platform_release
}

push_marketplace_web() {
  docker_push clients/marketplace-web/Dockerfile marketplace-web
  PLATFORM_DIGEST_BACKEND="$(registry_digest backend)"
  PLATFORM_DIGEST_MARKETPLACE="$(registry_digest marketplace)"
  PLATFORM_DIGEST_RELAY="$(registry_digest relay)"
  PLATFORM_DIGEST_WEB="$(registry_digest web)"
  PLATFORM_DIGEST_WEB_ADMIN="$(registry_digest web-admin)"
  write_platform_release
}

push_infra() {
  mirror pgvector/pgvector:pg16 pgvector:pg16
  mirror redis:7-alpine         redis:7-alpine
  mirror minio/minio:latest     minio:latest
  mirror minio/mc:latest        mc:latest
  mirror alpine/k8s:1.28.4      kubectl:1.28
}

push_runners() {
  ( cd "${REPO_ROOT}" && bash docker/agent-runtime/build.sh claude-code )
  ( cd "${REPO_ROOT}" && bash docker/agent-runtime/build.sh codex-cli )
  ( cd "${REPO_ROOT}" && bash docker/agent-runtime/build.sh gemini-cli )
  ( cd "${REPO_ROOT}" && bash docker/agent-runtime/build.sh grok-build )
  ( cd "${REPO_ROOT}" && bash docker/agent-runtime/build.sh openclaw )
  ( cd "${REPO_ROOT}" && bash docker/agent-runtime/build.sh hermes )
  docker build --platform linux/amd64 --target runtime \
    -f "${REPO_ROOT}/docker/agent-runtime/Dockerfile" \
    --build-arg AGENT_RUNTIME=e2e-echo \
    -t do-worker/runner-e2e-echo:latest \
    "${REPO_ROOT}/docker/agent-runtime/_context"
  if docker image inspect "do-worker/runner-minimax-cli:latest" >/dev/null 2>&1; then
    :
  elif docker image inspect "l8ai/runner-minimax-cli:latest" >/dev/null 2>&1; then
    docker tag "l8ai/runner-minimax-cli:latest" "do-worker/runner-minimax-cli:latest"
  else
    docker build --platform linux/amd64 --target runtime \
      -f "${REPO_ROOT}/docker/agent-runtime/Dockerfile" \
      --build-arg AGENT_RUNTIME=minimax-cli \
      -t do-worker/runner-minimax-cli:latest \
      "${REPO_ROOT}/docker/agent-runtime/_context"
  fi
  for rt in claude-code codex-cli gemini-cli grok-build openclaw hermes e2e-echo minimax-cli; do
    docker tag "do-worker/runner-${rt}:latest" "${PROJ}/runner-${rt}:latest"
    docker push "${PROJ}/runner-${rt}:latest"
  done
}

main() {
  ensure_project
  case "${TARGET}" in
    platform) push_platform ;;
    marketplace-core) push_marketplace_core ;;
    mobile-access) push_mobile_access ;;
    web)      push_web ;;
    marketplace-web) push_marketplace_web ;;
    infra)    push_infra ;;
    runners)  push_runners ;;
    all)      push_platform; push_infra; push_runners ;;
    *) echo "usage: $0 [all|platform|marketplace-core|mobile-access|web|marketplace-web|infra|runners]" >&2; exit 1 ;;
  esac
  echo "==> done: ${TARGET}"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
