//! Client-facing proto domains (mirrors types/BUILD.bazel; excludes runner/v1).

pub struct Domain {
    pub name: &'static str,
    pub srcs: &'static [&'static str],
    pub deps: &'static [&'static str],
}

pub const DOMAINS: &[Domain] = &[
    Domain { name: "agent", srcs: &["agent.proto"], deps: &[] },
    Domain { name: "ai_resource", srcs: &["ai_resource.proto", "types.proto"], deps: &[] },
    Domain { name: "execution_cluster", srcs: &["execution_cluster.proto"], deps: &[] },
    Domain { name: "apikey", srcs: &["api_key.proto"], deps: &[] },
    Domain { name: "app_state", srcs: &["app_state.proto"], deps: &[] },
    Domain { name: "auth", srcs: &["auth.proto"], deps: &[] },
    Domain { name: "org", srcs: &["org.proto"], deps: &[] },
    Domain { name: "auth_state", srcs: &["auth_state.proto"], deps: &["auth", "org"] },
    Domain { name: "autopilot", srcs: &["autopilot.proto"], deps: &[] },
    Domain { name: "billing", srcs: &["billing.proto", "billing_admin.proto"], deps: &[] },
    Domain { name: "binding", srcs: &["binding.proto"], deps: &[] },
    Domain { name: "blockstore", srcs: &["blockstore.proto"], deps: &[] },
    Domain { name: "blockstore_state", srcs: &["blockstore_state.proto"], deps: &["blockstore"] },
    Domain { name: "channel", srcs: &["channel.proto"], deps: &[] },
    Domain {
        name: "pod",
        srcs: &[
            "agentpod_settings.proto",
            "worker_creation.proto",
            "worker_skill_publish.proto",
            "pod.proto",
        ],
        deps: &[],
    },
    Domain { name: "channel_state", srcs: &["channel_state.proto", "mutations.proto"], deps: &["pod"] },
    Domain { name: "env_bundle", srcs: &["env_bundle.proto"], deps: &[] },
    Domain {
        name: "extension",
        srcs: &["market.proto", "repo_mcp.proto", "repo_skill.proto"],
        deps: &[],
    },
    Domain { name: "events", srcs: &["event_data.proto", "events.proto"], deps: &[] },
    Domain { name: "file", srcs: &["file.proto"], deps: &[] },
    Domain { name: "grant", srcs: &["grant.proto"], deps: &[] },
    Domain { name: "invitation", srcs: &["invitation.proto"], deps: &[] },
    Domain { name: "knowledgebase", srcs: &["knowledgebase.proto"], deps: &[] },
    Domain { name: "license", srcs: &["license.proto"], deps: &[] },
    Domain { name: "goalloop", srcs: &["goalloop.proto"], deps: &[] },
    Domain { name: "workflow", srcs: &["workflow.proto"], deps: &[] },
    Domain { name: "workflow_state", srcs: &["workflow_state.proto"], deps: &["workflow"] },
    Domain { name: "mesh", srcs: &["mesh.proto"], deps: &[] },
    Domain { name: "mesh_state", srcs: &["mesh_state.proto"], deps: &["mesh"] },
    Domain { name: "notification", srcs: &["notification.proto"], deps: &[] },
    Domain {
        name: "orchestration_resource",
        srcs: &["orchestration_resource.proto"],
        deps: &[],
    },
    Domain { name: "pod_state", srcs: &["pod_state.proto"], deps: &["pod"] },
    Domain { name: "promocode", srcs: &["promocode.proto", "promocode_admin.proto"], deps: &[] },
    Domain { name: "repository", srcs: &["repository.proto"], deps: &[] },
    Domain { name: "repo_state", srcs: &["repo_state.proto"], deps: &["repository"] },
    Domain { name: "runner_api", srcs: &["runner.proto"], deps: &[] },
    Domain { name: "runner_state", srcs: &["runner_state.proto"], deps: &["runner_api"] },
    Domain { name: "autopilot_state", srcs: &["autopilot_state.proto"], deps: &[] },
    Domain { name: "acp_state", srcs: &["acp_state.proto"], deps: &[] },
    Domain { name: "sso", srcs: &["sso.proto", "sso_admin.proto"], deps: &[] },
    Domain { name: "support_ticket", srcs: &["support_ticket.proto", "support_ticket_admin.proto"], deps: &[] },
    Domain { name: "ticket", srcs: &["ticket.proto"], deps: &[] },
    Domain { name: "ticket_state", srcs: &["ticket_state.proto"], deps: &["ticket"] },
    Domain { name: "ticket_relations", srcs: &["ticket_relations.proto"], deps: &[] },
    Domain { name: "token_usage", srcs: &["token_usage.proto"], deps: &[] },
    Domain { name: "user", srcs: &["user.proto"], deps: &[] },
    Domain { name: "user_credential", srcs: &["user_credential.proto"], deps: &[] },
];
