/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ExpertsExpertIdRouteImport } from './routes/experts.$expertId'
import { Route as SessionsSessionIdTerminalRouteImport } from './routes/sessions.$sessionId.terminal'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsExpertIdRoute = ExpertsExpertIdRouteImport.update({
  id: '/$expertId',
  path: '/$expertId',
  getParentRoute: () => ExpertsRoute,
} as any)
const SessionsSessionIdTerminalRoute =
  SessionsSessionIdTerminalRouteImport.update({
    id: '/terminal',
    path: '/terminal',
    getParentRoute: () => SessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/experts': typeof ExpertsRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/new': typeof NewRoute
  '/experts/$expertId': typeof ExpertsExpertIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/sessions/$sessionId/terminal': typeof SessionsSessionIdTerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/experts': typeof ExpertsRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/new': typeof NewRoute
  '/experts/$expertId': typeof ExpertsExpertIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/sessions/$sessionId/terminal': typeof SessionsSessionIdTerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/experts': typeof ExpertsRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/new': typeof NewRoute
  '/experts/$expertId': typeof ExpertsExpertIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/sessions/$sessionId/terminal': typeof SessionsSessionIdTerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/experts'
    | '/login'
    | '/me'
    | '/new'
    | '/experts/$expertId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/experts'
    | '/login'
    | '/me'
    | '/new'
    | '/experts/$expertId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/terminal'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/experts'
    | '/login'
    | '/me'
    | '/new'
    | '/experts/$expertId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/sessions/$sessionId'
    | '/sessions/$sessionId/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  ExpertsRoute: typeof ExpertsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  NewRoute: typeof NewRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts/$expertId': {
      id: '/experts/$expertId'
      path: '/$expertId'
      fullPath: '/experts/$expertId'
      preLoaderRoute: typeof ExpertsExpertIdRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/sessions/$sessionId/terminal': {
      id: '/sessions/$sessionId/terminal'
      path: '/terminal'
      fullPath: '/sessions/$sessionId/terminal'
      preLoaderRoute: typeof SessionsSessionIdTerminalRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
  }
}

interface ExpertsRouteChildren {
  ExpertsExpertIdRoute: typeof ExpertsExpertIdRoute
}

const ExpertsRouteChildren: ExpertsRouteChildren = {
  ExpertsExpertIdRoute: ExpertsExpertIdRoute,
}

const ExpertsRouteWithChildren =
  ExpertsRoute._addFileChildren(ExpertsRouteChildren)

interface SessionsSessionIdRouteChildren {
  SessionsSessionIdTerminalRoute: typeof SessionsSessionIdTerminalRoute
}

const SessionsSessionIdRouteChildren: SessionsSessionIdRouteChildren = {
  SessionsSessionIdTerminalRoute: SessionsSessionIdTerminalRoute,
}

const SessionsSessionIdRouteWithChildren =
  SessionsSessionIdRoute._addFileChildren(SessionsSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  ExpertsRoute: ExpertsRouteWithChildren,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  NewRoute: NewRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  SessionsSessionIdRoute: SessionsSessionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
