package agentpod

import (
	agentDomain "github.com/anthropics/agentsmesh/backend/internal/domain/agent"
	"github.com/anthropics/agentsmesh/backend/internal/domain/agentpod"
	specservice "github.com/anthropics/agentsmesh/backend/internal/service/workerspec"
)

// CreatePodRequest represents a pod creation request
type CreatePodRequest struct {
	OrganizationID    int64
	RunnerID          int64
	ClusterID         int64
	AgentSlug         string
	RepositoryID      *int64
	TicketID          *int64
	CreatedByID       int64
	Prompt            string
	Alias             *string
	BranchName        *string
	Model             string
	PermissionMode    string
	SkipPermissions   bool
	PreparationConfig *agentpod.PreparationConfig
	EnvVars           map[string]string
	ResolvedConfig    agentDomain.ConfigValues

	// Resume related fields
	SessionID    string // Session ID for agent session management (generated by Backend)
	SourcePodKey string // Original pod key when creating via resume

	// Interaction mode: "pty" (default) or "acp"
	InteractionMode string

	// AutomationLevel is the unified permission/automation tier
	// (interactive/auto_edit/autonomous). Empty ⇒ autonomous default.
	AutomationLevel string

	// Perpetual mode: Runner auto-restarts the agent process on clean exit
	Perpetual bool

	InitialStatus string

	// VirtualAPIKeyID attributes usage to a virtual API key for quota/billing.
	VirtualAPIKeyID *int64
	ModelResourceID *int64
	AgentfileLayer  string
	PreviewPort     int
	PreviewPath     string

	ResolvedWorkerSpec   *specservice.ResolvedSnapshot
	WorkerSpecSnapshotID *int64
}
