import type { AgentWorkspaceText } from "./agentWorkspaceText";
import {
  englishConfigurationLabel,
  englishConfigurationOption,
  localizeConfigurationLabel,
  localizeConfigurationOption,
} from "./configurationLocalization";
import {
  chineseActivityStatus,
  chineseSessionStatus,
  englishActivityStatus,
  englishSessionStatus,
} from "./agentStatusText";
import { localizeToolText } from "./toolLocalization";
import {
  chineseToolActivityGroupSummary,
  englishToolActivityGroupSummary,
} from "./toolActivityGroupText";
import { artifactWorkspaceText } from "./artifactWorkspaceText";
import {
  chineseVideoTaskStatus,
  englishVideoTaskStatus,
} from "./videoTaskStatusText";

export const englishAgentWorkspaceText: AgentWorkspaceText = {
  conversation: "Conversation",
  results: "Results",
  artifacts: "Artifacts",
  workspaceViews: "Workspace views",
  terminal: "Terminal",
  plan: "Plan",
  agentPlan: "Agent plan",
  loadEarlierActivity: "Load earlier activity",
  readyForTask: "Ready for a task",
  startSession: "Send a message to start this agent session.",
  you: "You",
  agent: "Agent",
  system: "System",
  agentic: "Agentic",
  terminalMode: "Terminal mode",
  approvals: "Approvals",
  messageAgent: "Message the agent",
  readOnly: "This session is read-only",
  stopAgent: "Stop agent",
  sendMessage: "Send message",
  addAttachment: "Add attachment",
  removeAttachment: "Remove attachment",
  uploadingAttachment: "Uploading attachment",
  attachmentUploadFailed: "Could not upload the attachment. Try again.",
  attachmentUploadUnsupported:
    "This attachment type is not supported by the current session.",
  reject: "Reject",
  approve: "Approve",
  submitAnswers: "Submit answers",
  customAnswer: "Custom answer",
  details: "Details",
  takeControl: "Take control",
  releaseControl: "Release control",
  taskFailed: "The task failed. No verified result is available.",
  userProgressTitle: "Generation progress",
  unsupportedToolPreview:
    "No specialized preview is registered. Raw tool evidence is available below.",
  rawToolEvidence: "Raw tool evidence",
  videoTaskStatus: englishVideoTaskStatus,
  artifact: artifactWorkspaceText("en-US"),
  generatedArtifact: "Generated artifact",
  emptyHeading: (agentLabel) => `${agentLabel}, what should we work on?`,
  composerPlaceholder: (agentLabel) => `Ask ${agentLabel} to work on a task…`,
  requiresArgument: (commandLabel) => `${commandLabel} requires an argument`,
  slashCommandAttachmentsUnsupported:
    "Slash commands cannot include attachments. Remove the attachments or send a regular message.",
  customAnswerFor: (prompt) => `Custom answer for ${prompt}`,
  loadingArtifact: (filename) => `Loading ${filename}`,
  previewArtifact: (filename) => `Preview ${filename}`,
  videoPreview: (filename) => `Video preview for ${filename}`,
  openArtifact: (filename) => `Open ${filename}`,
  downloadArtifact: (filename) => `Download ${filename}`,
  configurationOptions: (label) => `${label} options`,
  configurationLabel: englishConfigurationLabel,
  configurationOption: englishConfigurationOption,
  sessionStatus: englishSessionStatus,
  activityStatus: englishActivityStatus,
  artifactType: (_kind, fallback) => fallback,
  toolText: (value) => value,
  toolActivityGroupSummary: englishToolActivityGroupSummary,
};

export const chineseAgentWorkspaceText: AgentWorkspaceText = {
  conversation: "对话",
  results: "成果",
  artifacts: "成果列表",
  workspaceViews: "工作区视图",
  terminal: "终端",
  plan: "执行计划",
  agentPlan: "智能体执行计划",
  loadEarlierActivity: "加载更早记录",
  readyForTask: "可以开始任务",
  startSession: "发送消息以启动智能体会话。",
  you: "你",
  agent: "智能体",
  system: "系统",
  agentic: "智能体模式",
  terminalMode: "终端模式",
  approvals: "请求审批",
  messageAgent: "给智能体发送消息",
  readOnly: "此会话为只读状态",
  stopAgent: "停止智能体",
  sendMessage: "发送消息",
  addAttachment: "添加附件",
  removeAttachment: "移除附件",
  uploadingAttachment: "正在上传附件",
  attachmentUploadFailed: "附件上传失败，请重试。",
  attachmentUploadUnsupported: "当前会话不支持此附件类型。",
  reject: "拒绝",
  approve: "批准",
  submitAnswers: "提交回答",
  customAnswer: "自定义回答",
  details: "详细信息",
  takeControl: "接管终端",
  releaseControl: "释放控制",
  taskFailed: "任务执行失败，当前没有可验证的成果。",
  userProgressTitle: "生成过程",
  unsupportedToolPreview:
    "未注册专用工具预览，以下保留原始工具证据。",
  rawToolEvidence: "原始工具证据",
  videoTaskStatus: chineseVideoTaskStatus,
  artifact: artifactWorkspaceText("zh-CN"),
  generatedArtifact: "生成的成果",
  emptyHeading: (agentLabel) => `${agentLabel}，我能为你做什么？`,
  composerPlaceholder: (agentLabel) => `让 ${agentLabel} 帮你完成任务…`,
  requiresArgument: (commandLabel) => `${commandLabel} 需要填写参数`,
  slashCommandAttachmentsUnsupported:
    "斜杠命令不能携带附件。请移除附件，或改为发送普通消息。",
  customAnswerFor: (prompt) => `${prompt}的自定义回答`,
  loadingArtifact: (filename) => `正在加载 ${filename}`,
  previewArtifact: (filename) => `预览 ${filename}`,
  videoPreview: (filename) => `${filename} 的视频预览`,
  openArtifact: (filename) => `打开 ${filename}`,
  downloadArtifact: (filename) => `下载 ${filename}`,
  configurationOptions: (label) => `${label}选项`,
  configurationLabel: localizeConfigurationLabel,
  configurationOption: localizeConfigurationOption,
  sessionStatus: chineseSessionStatus,
  activityStatus: chineseActivityStatus,
  artifactType: (kind, fallback) =>
    ({
      "HTML document": "HTML 文档",
      "SVG document": "SVG 文档",
      Image: "图片",
      Video: "视频",
      PDF: "PDF 文档",
      PowerPoint: "PowerPoint 演示文稿",
      "Code file": "代码文件",
      "Text file": "文本文件",
      File: "文件",
    })[kind] ?? fallback,
  toolText: localizeToolText,
  toolActivityGroupSummary: chineseToolActivityGroupSummary,
};
