import { workforceScenarios } from './workforce-scenarios'

const componentMessageKeys = [
  'landing.workforce.hero.badge',
  'landing.workforce.hero.titleLead',
  'landing.workforce.hero.titleEmphasis',
  'landing.workforce.hero.description',
  'landing.workforce.hero.watchTeam',
  'landing.workforce.hero.startFree',
  'landing.workforce.mission.console',
  'landing.workforce.mission.goal',
  'landing.workforce.mission.scenarios',
  'landing.workforce.mission.workers',
  'landing.workforce.mission.activity',
  'landing.workforce.mission.checkpoint',
  'landing.workforce.mission.checkpointDetail',
  'landing.workforce.mission.progress',
  'landing.workforce.mission.deliverable',
  'landing.workforce.mission.pause',
  'landing.workforce.mission.resume',
  'landing.workforce.mission.nextStep',
  'landing.workforce.mission.replay',
  'landing.workforce.scenarioLabels.research',
  'landing.workforce.scenarioLabels.content',
  'landing.workforce.scenarioLabels.operations',
  'landing.workforce.scenarioLabels.sales',
  'landing.workforce.scenarioLabels.knowledge',
  'landing.workforce.scenarioLabels.product',
  'landing.workforce.showcase.eyebrow',
  'landing.workforce.showcase.title',
  'landing.workforce.showcase.description',
  'landing.workforce.showcase.scenarioPicker',
  'landing.workforce.showcase.goal',
  'landing.workforce.showcase.workers',
  'landing.workforce.showcase.workflow',
  'landing.workforce.showcase.deliverable',
  'landing.workforce.lifecycle.eyebrow',
  'landing.workforce.lifecycle.title',
  'landing.workforce.lifecycle.description',
  'landing.workforce.lifecycle.stages.goal.title',
  'landing.workforce.lifecycle.stages.goal.description',
  'landing.workforce.lifecycle.stages.coordinate.title',
  'landing.workforce.lifecycle.stages.coordinate.description',
  'landing.workforce.lifecycle.stages.review.title',
  'landing.workforce.lifecycle.stages.review.description',
  'landing.workforce.lifecycle.stages.deliver.title',
  'landing.workforce.lifecycle.stages.deliver.description',
  'landing.workforce.lifecycle.fragments.ticket.id',
  'landing.workforce.lifecycle.fragments.ticket.status',
  'landing.workforce.lifecycle.fragments.ticket.title',
  'landing.workforce.lifecycle.fragments.channel.name',
  'landing.workforce.lifecycle.fragments.channel.activity',
  'landing.workforce.lifecycle.fragments.checkpoint.status',
  'landing.workforce.lifecycle.fragments.checkpoint.decision',
  'landing.workforce.lifecycle.fragments.checkpoint.action',
  'landing.workforce.lifecycle.fragments.evidence.pod',
  'landing.workforce.lifecycle.fragments.evidence.status',
  'landing.workforce.lifecycle.fragments.evidence.artifact',
  'landing.workforce.lifecycle.fragments.evidence.detail',
  'landing.workforce.capabilities.eyebrow',
  'landing.workforce.capabilities.title',
  'landing.workforce.capabilities.description',
  'landing.workforce.capabilities.items.organize.title',
  'landing.workforce.capabilities.items.organize.description',
  'landing.workforce.capabilities.items.organize.primitives.roles',
  'landing.workforce.capabilities.items.organize.primitives.tasks',
  'landing.workforce.capabilities.items.organize.primitives.ownership',
  'landing.workforce.capabilities.items.organize.primitives.context',
  'landing.workforce.capabilities.items.observe.title',
  'landing.workforce.capabilities.items.observe.description',
  'landing.workforce.capabilities.items.observe.primitives.activity',
  'landing.workforce.capabilities.items.observe.primitives.evidence',
  'landing.workforce.capabilities.items.observe.primitives.status',
  'landing.workforce.capabilities.items.observe.primitives.deliverables',
  'landing.workforce.capabilities.items.control.title',
  'landing.workforce.capabilities.items.control.description',
  'landing.workforce.capabilities.items.control.primitives.permissions',
  'landing.workforce.capabilities.items.control.primitives.checkpoints',
  'landing.workforce.capabilities.items.control.primitives.credentials',
  'landing.workforce.capabilities.items.control.primitives.audit',
  'landing.workforce.capabilities.items.operate.title',
  'landing.workforce.capabilities.items.operate.description',
  'landing.workforce.capabilities.items.operate.primitives.execution',
  'landing.workforce.capabilities.items.operate.primitives.schedules',
  'landing.workforce.capabilities.items.operate.primitives.workflows',
  'landing.workforce.trust.eyebrow',
  'landing.workforce.trust.title',
  'landing.workforce.trust.description',
  'landing.workforce.trust.safeguards.selfHosting.title',
  'landing.workforce.trust.safeguards.selfHosting.description',
  'landing.workforce.trust.safeguards.selfHosting.status',
  'landing.workforce.trust.safeguards.workspaces.title',
  'landing.workforce.trust.safeguards.workspaces.description',
  'landing.workforce.trust.safeguards.workspaces.status',
  'landing.workforce.trust.safeguards.credentials.title',
  'landing.workforce.trust.safeguards.credentials.description',
  'landing.workforce.trust.safeguards.credentials.status',
  'landing.workforce.trust.safeguards.audit.title',
  'landing.workforce.trust.safeguards.audit.description',
  'landing.workforce.trust.safeguards.audit.status',
  'landing.workforce.trust.compatibility.title',
  'landing.workforce.trust.compatibility.description',
] as const

const scenarioMessageKeys = workforceScenarios.flatMap((scenario) => [
  scenario.goalKey,
  ...scenario.workers,
  ...scenario.steps,
  scenario.deliverableKey,
])

export const requiredWorkforceMessageKeys = [
  ...componentMessageKeys,
  ...scenarioMessageKeys,
] as const

export type WorkforceMessageKey = (typeof requiredWorkforceMessageKeys)[number]
