const root = "landing.workforce.expertHome";

const fixedKeys = [
  "hero.eyebrow",
  "hero.title",
  "hero.description",
  "hero.primaryAction",
  "hero.secondaryAction",
  "hero.proof",
  "console.title",
  "console.status",
  "console.live",
  "console.paused",
  "console.complete",
  "console.goalLabel",
  "console.goal",
  "console.expertLabel",
  "console.expert",
  "console.formulaLabel",
  "console.formula",
  "console.workflowLabel",
  "console.steps",
  "console.checkpointLabel",
  "console.checkpoint",
  "console.deliverableLabel",
  "console.deliverable",
  "console.controls.pause",
  "console.controls.resume",
  "console.controls.next",
  "console.controls.replay",
  "solutions.eyebrow",
  "solutions.title",
  "solutions.description",
  "solutions.workflowLabel",
  "solutions.deliverablesLabel",
  "solutions.items",
  "capabilities.eyebrow",
  "capabilities.title",
  "capabilities.description",
  "capabilities.levels.implemented",
  "capabilities.levels.composable",
  "capabilities.levels.planned",
  "capabilities.items",
  "operating.eyebrow",
  "operating.title",
  "operating.description",
  "operating.formulaTitle",
  "operating.parts",
  "operating.humanTitle",
  "operating.humanDescription",
  "operating.humanItems",
  "market.eyebrow",
  "market.title",
  "market.description",
  "market.apps",
  "market.status",
  "market.plannedTitle",
  "market.plannedDescription",
  "market.action",
  "trust.eyebrow",
  "trust.title",
  "trust.description",
  "trust.items",
  "trust.runtimesTitle",
  "trust.runtimesDescription",
  "cta.eyebrow",
  "cta.title",
  "cta.description",
  "cta.primary",
  "cta.secondary",
] as const;

export const requiredExpertHomeMessageKeys = [
  ...fixedKeys,
].map((key) => `${root}.${key}`);
